// SPDX-License-Identifier: MIT
pragma solidity ^0.8.27;

/**
 * @title IUltraVerifier
 * @notice Interface for UltraHonk proof verifier
 * @dev Generated verifier contract must implement this interface
 */
interface IUltraVerifier {
    /**
     * @notice Verify an UltraHonk proof
     * @param _proof The proof bytes generated by the circuit
     * @param _publicInputs Array of public inputs (324 fields for Mintmarks circuit)
     * @return True if the proof is valid, false otherwise
     */
    function verify(bytes calldata _proof, bytes32[] calldata _publicInputs) external view returns (bool);
}
